name: Test workflow

on:
  issue_comment:
    types:
      - created
  # Run every 15 min
  schedule:
    - cron:  '0/15 * * * *'

concurrency:
  group: "${{ github.workflow }} ${{ github.event.issue.pull_request.url || 'scheduled' }} ${{ github.event.comment.body }}"
  cancel-in-progress: true

jobs:
  check_changes:
    name: Deduce required tests from code changes
    runs-on: ubuntu-latest
    outputs:
      tested: ${{ steps.tested-tree.outputs.src }}
      pr-base: ${{ steps.pr.outputs.base }}
      pr-head: ${{ steps.pr.outputs.head }}
    steps:
      - name: Checkout code
        if: ${{ github.event.issue.pull_request }}
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 1
      - id: pr
        if: ${{ github.event.issue.pull_request }}
        run: |
          curl ${{ github.event.issue.pull_request.url }} > pr.json
          echo "::set-output name=base::$(jq -r '.base.sha' pr.json)"
          echo "::set-output name=head::$(jq -r '.head.sha' pr.json)"
      - uses: dorny/paths-filter@v2
        if: ${{ github.event.issue.pull_request }}
        id: tested-tree
        with:
          base: ${{ steps.pr.outputs.base }}
          ref: ${{ steps.pr.outputs.head }}
          filters: |
            src:
              - '!(test|Documentation)/**'

  build_commits:
    needs: check_changes
    if: needs.check_changes.outputs.tested == 'true'
    name: Test concurrency group
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - run: |
          echo "${{ needs.check_changes.outputs.pr-base }}..${{ needs.check_changes.outputs.pr-head }}"
      - run: |
          sleep 120
      - run: |
          echo "Finished!"
