name: Test workflow

on:
  issue_comment:
    types:
      - created
  # Run every 15 min
  schedule:
    - cron:  '0 11 * * *'

concurrency:
  group: "${{ github.workflow }} ${{ github.event.issue.pull_request.url || 'scheduled' }}"
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      tested: ${{ steps.tested-tree.outputs.src }}
      pr-base: ${{ steps.pr.outputs.base }}
      pr-head: ${{ steps.pr.outputs.head }}
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      #   with:
      #     persist-credentials: false
      #     ref: ${{ github.event.pull_request.head.sha }}
      #     fetch-depth: 0
      - id: pr
        run: |
          curl ${{ github.event.issue.pull_request.url }} > pr.json
          echo "::set-output name=base::$(jq -r '.base.sha' pr.json)"
          echo "::set-output name=head::$(jq -r '.head.sha' pr.json)"
      - uses: dorny/paths-filter@v2
        id: tested-tree
        with:
          base: ${{ steps.pr.outputs.base }}
          ref: ${{ steps.pr.outputs.head }}
          filters: |
            src:
              - '!(test|Documentation)/**'

  build_commits:
    needs: changes
    if: needs.changes.outputs.tested == 'true'
    name: Test concurrency group
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - run: |
          echo "${{ needs.changes.outputs.pr-base }}..${{ needs.changes.outputs.pr-head }}"
      - run: |
          sleep 60
      - run: |
          echo "Finished!"
