name: Test workflow

on:
  issues:
    types:
      - labeled

jobs:
  build_commits:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - run: |
          echo "Yeyha!"
          ./update-project.sh ${{ github.event.label.name }}
