name: Test workflow

on:
  issue_comment:
    types:
      - created
  # Run every 15 min
  schedule:
    - cron:  '*/15 * * * *'

concurrency:
  group: ${{ github.workflow }}${{ github.event.issue.pull_request && github.event.issue.pull_request.number || 'scheduled' }}
  cancel-in-progress: true

jobs:
  build_commits:
    name: Test concurrency group
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - run: |
          echo ${{ github.workflow }}${{ github.event.issue.pull_request && github.event.issue.pull_request.number || 'scheduled' }}
      - run: |
          sleep 600
      - run: |
          echo "Finished!"
