name: Test workflow

on:
  issue_comment:
    types:
      - created
  # Run every 15 min
  schedule:
    - cron:  '0/15 * * * *'

concurrency:
  group: "${{ github.workflow }} ${{ github.event.issue.pull_request.url || 'scheduled' }}"
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      tested: ${{ steps.tested-tree.outputs.src }}
    steps:
      - name: Checkout code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: dorny/paths-filter@v2
        id: tested-tree
        with:
          base: ${{ github.event.issue.pull_request.base.sha }}
          filters: |
            src:
              - '!(test|Documentation)/**'

  build_commits:
    needs: changes
    if: needs.changes.outputs.tested == 'true'
    name: Test concurrency group
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - run: |
          echo "${{ toJSON(github.event) }}"
      - run: |
          sleep 60
      - run: |
          echo "Finished!"
