name: Test workflow

on:
  pull_request: {}
  push:
    branches:
      - master

concurrency:
  group: ${{ github.event.pull_request && github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  build_commits:
    name: Test concurrency group
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - run: |
          echo "${{ github.event.pull_request && github.event.pull_request.number || github.event.after }}"
      - run: |
          sleep 600
      - run: |
          echo "Finished!"
